### ISSUE TITLE
Load the XML package in Rstudio by default.

### ISSUE THREAD

**Issue by jimmylovestea** [mobilizingcs-ops/chef-cens-rstudio#6]
@stevenolen the package is installed but I'd like to have it loaded by default.

**Comment by stevenolen** [comment]
adding XML seems to have a distinct increase in memory usage per student. How required is this? We're already a bit at upper bounds for student usage limits...

``` r
> gc()
         used (Mb) gc trigger (Mb) max used (Mb)
Ncells 534817 28.6     940480 50.3   750400 40.1
Vcells 723794  5.6    1308461 10.0   829316  6.4
> library(XML)
> 
> gc()
         used (Mb) gc trigger (Mb) max used (Mb)
Ncells 613592 32.8    1168576 62.5   940480 50.3
Vcells 782135  6.0    1650153 12.6  1308244 10.0
```

**Comment by stevenolen** [comment]
since it's already installed though, this is actually done in your package: https://github.com/mobilizingcs/mobilizr/blob/master/DESCRIPTION#L14-L27
